package model;

/**
 * Interface for components that wish to listen for events generated by the model layer.
 * Implementors of this interface can register themselves with model components
 * (like ICalendarManager) to be notified of changes.
 */
@FunctionalInterface // This is a functional interface as it has only one abstract method
public interface IModelEventListener {

    /**
     * Called when a model event occurs. Implementors should define how they
     * react to different types of model events.
     *
     * @param event The event object containing details about what happened in the model.
     */
    void onModelEvent(ModelEvent event);
}
