package model;

/**
 * Represents an event generated by the model layer, containing information
 * about the change that occurred.
 */
public class ModelEvent {

    /**
     * Defines the types of events that the model can generate.
     */
    public enum EventType {
        CALENDAR_CREATED,
        CALENDAR_EDITED,
        CALENDAR_SWITCHED,
        EVENT_ADDED,
        EVENT_EDITED,
        EVENT_DELETED,
        EXPORT_COMPLETED,
        IMPORT_COMPLETED,
        ERROR // For general errors or issues reported by the model
    }

    private final EventType type;
    private final String message;
    private final Object data; // Optional data associated with the event (e.g., the created calendar)

    /**
     * Constructs a new ModelEvent.
     *
     * @param type    The type of the event.
     * @param message A descriptive message about the event.
     * @param data    Optional data related to the event (can be null).
     */
    public ModelEvent(EventType type, String message, Object data) {
        this.type = type;
        this.message = message;
        this.data = data;
    }

    /**
     * Gets the type of the event.
     *
     * @return The event type.
     */
    public EventType getType() {
        return type;
    }

    /**
     * Gets the descriptive message associated with the event.
     *
     * @return The event message.
     */
    public String getMessage() {
        return message;
    }

    /**
     * Gets the optional data associated with the event.
     *
     * @return The event data, or null if no data is associated.
     */
    public Object getData() {
        return data;
    }

    @Override
    public String toString() {
        return "ModelEvent{" +
               "type=" + type +
               ", message='" + message + '\'' +
               ", data=" + data +
               '}';
    }
}
